export const TYPING_TEXT_BLOCKS: string[] = [
  "Consistent typing practice is not about rushing every line, but about building smooth control, steady rhythm, and reliable accuracy under pressure. A focused session starts with posture, relaxed shoulders, and clear attention on each word as it appears in front of you. As your pace improves, keep your breathing calm and your hands light so every keypress remains deliberate and clean. Small mistakes are expected, but fast recovery matters more than perfection because resilience keeps momentum alive during longer tests. Track your progress through speed, precision, and stability, then compare sessions to find patterns that help you improve with purpose. Over time, strong typists balance confidence with discipline, turning repeated practice into durable performance gains that transfer to writing, coding, communication, and day to day productivity.",
  "A reliable typing routine begins before your first keystroke with a comfortable position, neutral wrists, and a calm mental pace. Rather than forcing maximum speed from the start, build a smooth rhythm that keeps your timing steady through every sentence. Watch for common error patterns, especially repeated letter combinations, and treat those moments as training signals instead of setbacks. If you make a mistake, correct it quickly and continue without losing flow. Long term progress comes from consistency, not intensity, so short focused sessions done regularly will outperform random bursts of effort. As your accuracy improves, speed will follow naturally because clean muscle memory reduces hesitation and friction. Keep each run measurable, review your trends, and apply one clear improvement goal to the next test.",
  "Typing under time pressure rewards control more than raw force, which is why disciplined pacing is a stronger strategy than constant acceleration. Settle into a tempo where your fingers move confidently and your eyes stay one or two words ahead of the cursor. Avoid heavy key presses and unnecessary tension in your shoulders, since physical strain usually causes timing drift and avoidable errors. When your rhythm breaks, reset with one steady phrase and rebuild momentum instead of rushing to recover instantly. Accurate repetition across many sessions creates dependable speed because your hands begin to predict common patterns automatically. Track your strongest and weakest moments, then tune your practice toward consistency from the first second to the last. That approach turns typing from a quick test skill into a dependable professional advantage.",
  "Effective typing improvement comes from clear habits: maintain posture, stay relaxed, and use even breathing while you move through each line. Start every run with controlled intent rather than chasing a personal best immediately, because stable openings create stronger finishes. Keep your eyes active and let your hands follow established motion patterns instead of reacting late to each letter. Mistakes should be treated as temporary noise, not failure, and quick correction is usually better than emotional overreaction. The most reliable gains appear when you review outcomes honestly and make one practical adjustment before the next attempt. Over weeks of consistent practice, that feedback loop builds faster recognition, lower error rates, and steadier timing under pressure. Good typing is ultimately a blend of awareness, repeatability, and confidence supported by disciplined daily execution.",
  "Strong typists develop an internal rhythm that allows them to stay calm even when the timer is running and performance pressure rises. Instead of forcing every keystroke, they focus on predictable motion, balanced effort, and clean transitions between words. They keep visual attention slightly ahead, which reduces delay and prevents sudden pauses in the middle of a line. When an error appears, they respond quickly and continue with intent so the rest of the run remains efficient. This approach protects consistency across full sessions where stamina and focus matter as much as speed. Meaningful improvement is built by repeating quality reps, measuring outcomes, and refining one weakness at a time. With enough repetition, disciplined mechanics become automatic and typing quality stays high whether the task is coding, writing, research, or communication.",
  "Typing performance improves fastest when practice is structured around repeatable mechanics instead of random effort and short bursts of motivation. Begin with a stable posture, soft hands, and a comfortable breathing rhythm so your body supports precision rather than resistance. Work through each phrase with deliberate timing, and avoid chasing mistakes with panic because recovery speed matters more than perfect streaks. Keep your finger travel efficient, press keys with minimal force, and trust muscle memory for common patterns. Measure both speed and accuracy after every run, then review where rhythm dropped and where concentration stayed strongest. Use those findings to set one focused target for the next session. Over time, this method creates durable typing confidence that performs well in high workload situations without sacrificing readability, control, or composure.",
  "Fair typing tests should challenge memory, rhythm, and precision together, which is why varied passages help reveal genuine skill instead of memorized patterns. A good run starts with controlled pacing and clear visual tracking across the current line while your hands stay relaxed. The goal is not to sprint every word but to sustain accurate output from beginning to end without losing structure. When difficult combinations appear, keep your timing smooth and avoid overcorrecting with abrupt movement. Consistency in difficult moments often separates stable performers from inconsistent ones. Review your mistakes after the run and identify repeated sources of friction, then practice those patterns deliberately in later sessions. With steady repetition, the typing process becomes more efficient, and both speed and quality improve together in a measurable way.",
  "The most practical typing strategy is to prioritize clean execution, because accurate keystrokes reduce correction time and preserve momentum through longer tests. Keep your shoulders loose, wrists neutral, and attention centered on the upcoming words rather than the last mistake. Build a pace that feels controlled in the first lines, then maintain that tempo instead of oscillating between bursts and slowdowns. If focus slips, reset with a short sequence of deliberate strokes and continue forward. Long term progress comes from practicing with intention, analyzing outcomes, and repeating effective behaviors until they become default habits. Reliable typing is not accidental; it is built through disciplined sessions where each run produces useful feedback. That feedback loop steadily improves endurance, confidence, and consistency across all writing and coding tasks.",
  "Professional level typing feels smooth because it relies on coordination between vision, timing, and muscle memory rather than brute force speed. Your eyes should guide the next segment while your fingers complete the current one, creating continuous forward motion with minimal hesitation. To support that flow, keep key presses light and avoid unnecessary hand tension that can slow reaction time. Small errors are part of the process, but fast, calm correction prevents one mistake from affecting the rest of the run. Evaluate your session by looking at stability over time, not just the highest instant speed value. The strongest indicator of improvement is consistent control under pressure. As those habits mature, typing becomes more dependable, efficient, and transferable to real tasks that require both accuracy and pace.",
  "Training for better typing is most effective when you combine measurable goals with disciplined repetition and realistic pacing. Start each session with a clear objective, such as fewer mistakes or stronger timing in the final third of the test. Keep a steady tempo through familiar words and difficult sequences alike, because control during hard moments drives overall growth. Resist the urge to over accelerate after a clean streak; preserving rhythm usually leads to better final performance. Review your output and identify one specific adjustment before the next attempt, then test it immediately while feedback is fresh. This iterative method transforms practice into a reliable improvement system rather than random trial and error. Over many sessions, your speed rises naturally as accuracy, confidence, and endurance become stable.",
  "High quality typing is built on repeatable fundamentals: consistent posture, controlled breathing, smooth finger travel, and attention that stays anchored to the active text. Every session should reinforce these habits while challenging you enough to expose weak points. Treat the timer as a pacing guide instead of a source of panic, and let accuracy lead your speed decisions. When the flow breaks, recover with deliberate keystrokes and continue without frustration. The best performers improve because they review evidence, refine technique, and keep training sessions purposeful over time. They do not depend on lucky runs or memorized passages. By committing to this process, you develop durable typing ability that remains effective across different content, workloads, and real world communication tasks.",
  "Lasting typing growth happens when practice quality stays high from the first second to the final line, even as fatigue builds late in the run. Maintain a stable base by keeping your hands relaxed and your movements economical. Watch for words ahead of the cursor so your transitions remain fluid and your timing does not collapse under pressure. Accept occasional errors, correct them quickly, and protect overall rhythm rather than chasing perfection on each keystroke. Measure your sessions honestly, noting where pace dropped and where your focus remained consistent. Use that information to guide the next attempt with one clear improvement target. Repeated over weeks, this process builds dependable speed, cleaner accuracy, and strong composure in both testing and practical typing work.",
];

export function getRandomTypingText(previousText?: string): string {
  if (TYPING_TEXT_BLOCKS.length === 0) {
    return "";
  }

  if (TYPING_TEXT_BLOCKS.length === 1) {
    return TYPING_TEXT_BLOCKS[0];
  }

  const availableBlocks =
    previousText === undefined
      ? TYPING_TEXT_BLOCKS
      : TYPING_TEXT_BLOCKS.filter((block) => block !== previousText);

  const source = availableBlocks.length > 0 ? availableBlocks : TYPING_TEXT_BLOCKS;
  const randomIndex = Math.floor(Math.random() * source.length);

  return source[randomIndex];
}

export const DEFAULT_TEXT = getRandomTypingText();

export const TEST_DURATION = 60;
